### ISSUE TITLE
Fix webring on wickedcoolkit.com

### ISSUE THREAD

**Issue by crcastle** [fostive/wickedcoolkit.com#66]
This is what I currently see.

<img width="387" alt="CleanShot 2021-01-28 at 16 22 42@2x" src="https://user-images.githubusercontent.com/275734/106200542-2426cf80-6185-11eb-818b-ba14b3499a46.png">

I'm not sure which webring to update in our shared central salesforce org to add some sites to this webring. Can you help?

**Comment by lukekarrys** [comment]
Looks like this is using an incompatible soql query. Here's the error im getting. I think the query just needs to be updated for the schema

```
2021-01-28T21:54:33.118131+00:00 app[web.1]: JSForce Error: INVALID_TYPE: 
2021-01-28T21:54:33.118139+00:00 app[web.1]:             FROM Website_Webring_Association__c
2021-01-28T21:54:33.118139+00:00 app[web.1]:                  ^
2021-01-28T21:54:33.118140+00:00 app[web.1]: ERROR at Row:5:Column:18
2021-01-28T21:54:33.118148+00:00 app[web.1]: sObject type 'Website_Webring_Association__c' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.
2021-01-28T21:54:33.118149+00:00 app[web.1]:     at HttpApi.getError (/app/node_modules/jsforce/lib/http-api.js:250:13)
2021-01-28T21:54:33.118150+00:00 app[web.1]:     at /app/node_modules/jsforce/lib/http-api.js:95:22
2021-01-28T21:54:33.118150+00:00 app[web.1]:     at tryCallOne (/app/node_modules/promise/lib/core.js:37:12)
2021-01-28T21:54:33.118150+00:00 app[web.1]:     at /app/node_modules/promise/lib/core.js:123:15
2021-01-28T21:54:33.118151+00:00 app[web.1]:     at flush (/app/node_modules/asap/raw.js:50:29)
2021-01-28T21:54:33.118151+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:76:11) {
2021-01-28T21:54:33.118151+00:00 app[web.1]:   errorCode: 'INVALID_TYPE'
2021-01-28T21:54:33.118152+00:00 app[web.1]: }
```

**Comment by crcastle** [comment]
Just so it's documented here. Let's make the webring widget on *only* wickedcoolkit.com get its list of sites using this query

```sql
SELECT Id, Name, URL__c
FROM Website__c
WHERE Webring__c = 'a034x000002gA5YAAU'
```
